@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}

### Signup
POST {{host}}/users/signup
content-type: application/json

{ 
  "email": "test@example.com",
  "password": "abc123$$$",
  "confirm_password": "abc123$$$"
}

### Signin
POST {{host}}/users/login
content-type: application/json

{
  "email": "test@example.com",
  "password": "abc123$$$"
}