@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}

### Create a new products
POST {{host}}/users/signup
content-type: application/json

{ 
  "email": "test@example.com",
  "password": "abc123$$$",
  "confirm_password": "abc123$$$"
}