apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-mysql-present-volume
spec:
  storageClassName: webook
  capacity:
    storage: 1Gi
  # pv 支持的訪問模式
  accessModes:
    - ReadWriteOnce
  # 本pv的根目錄
  hostPath:
    path: "/mnt/data"