apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-app-mysql
  template:
    metadata:
      labels:
        app: social-media-app-mysql
    spec:
      containers:
      - name: social-media-app-mysql
        image: mysql:8.0.29
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        imagePullPolicy: IfNotPresent
        ports:
          - name: mysql
            containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql # mysql default data storage path
            name: mysql-storage
      restartPolicy: Always
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: social-media-app-mysql-present-volume-claim # pvc = persistent volume claim
