apiVersion: v1
kind: PersistentVolume
metadata:
  name: social-media-app-mysql-present-volume
spec:
  storageClassName: social-media-app
  capacity:
    storage: 1Gi
  # pv 支持的訪問模式
  accessModes:
    - ReadWriteOnce
  # 本pv的根目錄
  hostPath:
    path: "/mnt/data"