// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"social-media-app/internal/interface/web"
	"social-media-app/internal/repository"
	"social-media-app/internal/repository/dao"
	"social-media-app/internal/service"
	"social-media-app/ioc"
)

// Injectors from wire.go:

func InitApp() *App {
	cmdable := ioc.InitRedis()
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewUserRepository(userDAO)
	userService := service.NewUserService(userRepository)
	userHandler := web.NewUserHandler(userService)
	logger := ioc.InitLogger()
	draftArticleDao := dao.NewDraftArticleDao(logger, db)
	draftArticleRepository := repository.NewDraftArticleRepository(logger, draftArticleDao)
	articleService := service.NewArticleService(logger, draftArticleRepository)
	articleHandler := web.NewArticleHandler(logger, articleService)
	engine := ioc.InitWebServer(cmdable, userHandler, articleHandler)
	app := &App{
		webServer: engine,
	}
	return app
}
